
CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(150) UNIQUE NOT NULL,
	password VARCHAR(200) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP
);

CREATE TABLE items(
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	user_id INT REFERENCES users(id) ON DELETE CASCADE,
	is_deleted BOOLEAN DEFAULT false,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP
);

GRANT ALL PRIVILEGES ON TABLE users TO root;
GRANT ALL PRIVILEGES ON TABLE items TO root;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public to root;
